name: Create draft release

on:
  workflow_dispatch: 

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
  
      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test --verbose
        
  build:
    name: Build - ${{ matrix.os }}
    needs: test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gremlin-linux
          - os: windows-latest
            artifact_name: gremlin-windows
          - os: macos-latest
            artifact_name: gremlin-macos

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --locked --verbose

      - name: Rename binary
        shell: bash
        run: |
          mkdir -p staging-release
          cp target/release/gremlin staging-release/gremlin-${{ matrix.os }} || cp target/release/gremlin.exe staging-release/gremlin-${{ matrix.os }}.exe
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            staging-release/gremlin-${{ matrix.os }}
            staging-release/gremlin-${{ matrix.os }}.exe

  release:
    name: Create staging release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: staging-run-${{ github.run_number }}
          name: "Staging Release (Build #${{ github.run_number}})"
          files: |
            gremlin-linux/gremlin-ubuntu-latest
            gremlin-windows/gremlin-windows-latest.exe
            gremlin-macos/gremlin-macos-latest
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
